overwrite: true
schema: '../server/src/graphql/schema.graphql'
documents: 'src/**/*.{ts,tsx}'
generates:
  ./src/graphql/types.ts:
    config:
      scalars:
        objectId: String
    plugins:
      - 'add': '/* tslint:disable */'
      - 'typescript'
      - 'typescript-resolvers'
      - 'typescript-operations'
