overwrite: true
schema: './src/graphql/schema.graphql'
documents: null
watch:
  - './src/grpahql/schema.graphql'
generates:
  ./src/graphql/types.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
      - 'typescript-operations'
